config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [ :index, :show ]
  resources :arts, only: [ :index, :show, :new, :create, :destroy]
  resources :commissions do
    resources :requests, only: [:new, :create]
  end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :requests, only: [ :show] do
    get 'accept'
  end
  resources :payments, only: [ :show, :new, :create ]
  resources :orders, only: [:show, :create, :update] do
    resources :payments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, PhotoUploader
  validates :title, presence: true
  # validates :photo, presence: true
end

app/models/commission.rb
class Commission < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :requests, dependent: :destroy
  validates :title, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :request
  monetize :amount_cents
  mount_uploader :photo, PhotoUploader
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :commission
  belongs_to :user
  has_one :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :commissions, dependent: :destroy
  has_many :arts, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :orders


  def artist?
    unless self.arts.empty?
    return true
    end
  end

  def commissions_requests
    commissions.map { |commission| commission.requests }.flatten
  end

  def orders_as_commissioner
    return self.orders
  end

  def orders_as_commissionee
    orders = []
    requests.each do |request|
      unless request.order.nil?
        orders << request.order
      end
    end
    orders
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:bio])
  end

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  def show
    @art = Art.find(params[:id])
  end

  def new
    @art = Art.new
  end

  def create
    @art = Art.new(art_params)
    @art.user = current_user
    @art.save
    redirect_to art_path(@art)
  end

  def destroy
    @art = Art.find(params[:id])
    @art.delete
    redirect_to arts_path
  end

  def art_params
    params.require(:art).permit(:photo, :title)
  end
end

app/controllers/commissions_controller.rb
class CommissionsController < ApplicationController
  def index
    if params[:query].present?
      @commissions = Commission.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @commissions = Commission.all
    end
  end

  def show
    @commission = Commission.find(params[:id])
  end

  def new
    @commission = Commission.new
  end

  def create
    @commission = Commission.new(commission_params)
    @commission.user = current_user
    @commission.save
    redirect_to commission_path(@commission)
  end

  def edit
    @commission = Commission.find(params[:id])
  end

  def update
    @commission = Commission.find(params[:id])
    @commission.update(commission_params)
    redirect_to commission_path(@commission)
  end

  def destroy
    @commission = Commission.find(params[:id])
    @commission.delete
    redirect_to commissions_path
  end

  def accept
  end

  private

  def commission_params
    params.require(:commission).permit(:title, :description, :amount, :photo)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    request = Request.find(params[:request_id])
    order = Order.create!(request_sku: request.sku, amount: request.price_cents, state: 'pending', user: current_user, request: request)

    redirect_to new_order_payment_path(order)

  end

  def show
    @order = current_user.orders.where(state: 'paid').find(params[:id])
  end

  def update
    order = Order.find(params[:id])
    order.update(orders_params)
    flash[:notice] = "Your picture has been uploaded!"
    redirect_to user_path(current_user)
  end

  private

  def orders_params
    params.require(:order).permit(:photo, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order
  def new
  end

  def create
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @order.amount_cents,
      description:  "Payment for request #{@order.request_sku} for order #{@order.id}",
      currency:     @order.amount.currency
    )

    @order.update(payment: charge.to_json, state: 'paid')
    request = @order.request
    request.status = true
    request.save
    commission = @order.request.commission
    commission.requests.each do |request|
      unless request.status
        request.destroy
      end
    end
    commission.status = true
    commission.save

    flash[:notice] = 'Your artist is working on it'
    redirect_to commission_path(commission)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

  private

  def set_order
    @order = current_user.orders.where( state: 'pending').find(params[:order_id])
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  # def index
  #   @commission = Commission.find(params[:commission_id])
  #   @requests = @commission.requests
  # end

  def new
    @commission = Commission.find(params[:commission_id])
    @request = Request.new
  end

  def create
    @commission = Commission.find(params[:commission_id])
    @request = Request.new(request_params)
    @request.commission = Commission.find(params[:commission_id])
    @request.user = current_user
    @request.save
    flash[:notice] = "Request successfully created"
    redirect_to commission_path(@commission)
  end

  def show
    @request = Request.find(params[:id])
  end

  def accept
    @request = Request.find(params[:request_id])
    @commission = @request.commission
    @request.status = true
    @request.save
    @commission.status = true
    @commission.save
    @commission.requests.each do |request|
      unless request.status
        request.destroy
      end
    end
    redirect_to commission_path(@commission)
  end

  private

  def request_params
    params.require(:request).permit(:description, :price_cents, :status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if params[:query].present?
      sql_query = "first_name ILIKE :query OR last_name ILIKE :query"
      @users = User.where(sql_query, query: "%#{params[:query]}%")
    else
      @users = User.select { |user| user.arts }
    end
  end

  def show
    @user = User.find(params[:id])
    @orders = Order.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_type
    content_for?(:meta_type) ? content_for(:meta_type) : DEFAULT_META["meta_type"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/arts/new.html.erb
<div class="background-commission" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0) 50%), url('https://ohsooclean.com/wp-content/uploads/2018/06/testimonials.jpg');">
  <div class="container">

    <div class="com-container">
      <div class="com-card">
        <div>
          <h3>Your art:</h3>
        </div>
        <%= simple_form_for @art do |f| %>
        <div>
          <%= f.input :title, required: false,
            class: "com-title",
            placeholder: "Title..." %>
        </div>
        <div class="p-s">
          <div>
              <%= f.input :photo %>
              <%= f.input :photo_cache, as: :hidden %>
          </div>
          <div class="sub-btn sub-btn-margin">
            <%= f.button :submit,
            "Submit" %>
          </div>
        </div>


        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/arts/show.html.erb
<h1>Arts#show</h1>
<p>Find me in app/views/arts/show.html.erb</p>
<h1>More infos on <%= @art.title %></h1>
<%= cl_image_tag(@art.photo) %>

app/views/commissions/edit.html.erb
<h2>Edit Commission</h2>

  <%= form_for(@commission) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.label :amount %>
    <%= f.text_field :amount %>
    <%= f.label :photo %>
    <%= f.text_field :photo %>
    <%= f.submit %>
  <% end %>

app/views/commissions/index.html.erb
<div class="artist-search-container">
  <div class="artist-search-icon">
    <h5 class="fas fa-search"></h5>
  </div>
  <div class="artist-border">
    <%= form_tag commissions_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control artist-search",
      placeholder: "Find a commission"
  %>
  <% end %>
  </div>
</div>

<div class="container artist-container">
    <div class="row">
      <div class="col-xs-12 col-sm-7">
        <div class="artist-column commission-column">
          <% @commissions.select{ |commission| commission.id.even?}.each do |commission| %>
              <div class="com-index-card">
                <%= link_to commission_path(commission) do  %>
                  <div class="com-link"></div>
                  <div class="com-content">
                    <% if commission.amount %>
                      <div class="com-title">
                        <h5><%= commission.title %></h5>
                        <h5>£<%= commission.amount %></h5>
                      </div>
                        <p><%= commission.description %></p>
                      <% else %>
                        <h5><%= commission.title %></h5>
                        <p><%= commission.description %></p>
                      <% end %>
                  </div>
                <% end %>
              </div>
              <!-- <div class="card-break"><i class="fas fa-angle-double-down"></i></div> -->
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-5">
         <div class="artist-column commission-column">
           <% @commissions.select{|commission| commission.id.odd?}.each do |commission| %>
              <div class="com-index-card com-card-right">
                <%= link_to commission_path(commission) do  %>
                  <div class="com-link"></div>
                  <div class="com-content">
                    <% if commission.amount %>
                      <div class="com-title">
                        <h5><%= commission.title %></h5>
                        <h5>£<%= commission.amount %></h5>
                      </div>
                        <p><%= commission.description %></p>
                      <% else %>
                        <h5><%= commission.title %></h5>
                        <p><%= commission.description %></p>
                      <% end %>
                  </div>
                <% end %>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/commissions/new.html.erb
<div class="background-commission" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0) 50%), url('https://images.unsplash.com/photo-1503289130890-6eff9c5df553?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7d4ed6009e8a0e8b6948ebe612d5827f&auto=format&fit=crop&w=1050&q=80');">

  <div class="container">

    <div class="com-container">
      <div class="com-card">
        <div>
          <h3>Your commission:</h3>
        </div>
        <%= simple_form_for @commission do |f| %>
        <div>
            <%= f.input :title, required: false,
            class: "com-title",
            placeholder: "Title..." %>
        </div>
        <div>
            <%= f.input :description,
            class: "com-desription",
            placeholder: "Description..." %>
        </div>
        <div>
            <%= f.input :amount,
            class: "com-amount",
            placeholder: "Your budget (e.g. £300)..." %>
        </div>
        <div class="p-s">
          <div>
              <%= f.input :photo %>
              <%= f.input :photo_cache, as: :hidden %>
          </div>
          <div class="sub-btn sub-btn-margin">
            <%= f.button :submit,
            "Submit" %>
          </div>
        </div>


        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/commissions/show.html.erb
<div class="banner-show"></div>
<div class="commission-section">
  <div class="container">
    <div class="commission_box">
      <div class="commission_show_left">
        <h2> <%= @commission.title %></h2>
        <% if @commission.amount %>
          <h4>£<%= @commission.amount %></h4>
        <% end  %>
      </div>

      <div class="commission_show_right">
        <div class="commission_show-description">
          <h2>Description <%# @commission.description %></h2>
          <div class="commission-btns">
            <% if current_user.id == @commission.user.id %>
                <%= link_to "Edit", edit_commission_path(@commission), class: 'show-btn-commission' %>
                <%= link_to "Delete", commission_path(@commission), method: :delete, data: { confirm: "Delete commission?"}, class: 'show-btn-commission' %>
            <% else %>
              <%= link_to "Request Commission", new_commission_request_path(@commission), class: "show-btn-commission" %>
            <% end %>
          </div>
        </div>
        <h4><%= @commission.description %></h4>
      </div>
    </div>
    <% if @commission.photo %>
      <h3>Reference</h3>
      <div class="order-card">
        <div class="reference-image">
          <%= cl_image_tag(@commission.photo) %>
        </div>
          <div class="order-content">
            <h5 id="order-username">@<%= @commission.user.username %></h5>
            <p> Here's a Reference of what I want the picture to look like! </p>
        </div>
      </div>
    <% end %>

    <!-- <h2>Email:<%#= @commission.user.email %></h2> -->
    <div class="request-card-container">
      <% if current_user.id == @commission.user.id %>
        <% if @commission.status.nil? %>
          <% @commission.requests.each do |request| %>
          <h3>Requests</h3>
            <div class="request-card">
              <div class="request-content">
                <div class="request-content-header">
                  <h6><%= link_to "#{request.user.first_name} #{request.user.last_name}", user_path(request.user) %></h6>
                  <h6> Amount: <%=  humanized_money_with_symbol(request.price_cents) %></h6>
                </div>
                <p><%= request.description %></p>
              </div>
              <div class="request-btn">
                <%= link_to "Accept", orders_path(request_id: request.id), method: :post, class: 'show-btn-commission'  %>
                <%= link_to "Reject", commission_path(request.commission), class: 'show-btn-commission'  %>
              </div>
            </div>
          <% end %>
        <% elsif @commission.status %>
          <% if @commission.requests.first.order.photo_url.nil?  %>
          <% else %>
          <h3>Your Art.</h3>
            <div class="order-card">
              <div class="order-image">
                <%= cl_image_tag(@commission.requests.first.order.photo_url) %>
              </div>
                <div class="order-content">
                  <h5 id="order-username">@<%= @commission.requests.first.user.username %></h5>
                  <p><%= @commission.requests.first.order.message %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <!-- handles a true commission -->
      <% if @commission.status %>
        <% if current_user.id == @commission.requests.first.user %>
          <% if @commission.request.order.photo_url %>
            This commission has been completed!
          <% else %>
            <%= simple_form_for @commission.request.order do |f| %>
              <%= f.input :photo %>
              <%= f.input :photo_cache, as: :hidden %>
              <%= f.submit %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-270deg, rgba(0,0,0,1) 0%, rgba(0,0,0,0.5) 50%), url(<%= image_path 'video.gif'%>); background-size: cover;">
  <div class="banner-content">
    <div class="banner-title">

      <h1>Art.</h1>
      <h1>Commissions.</h1>
      <h1 class="home-h1">cART.</h1>
      <%= link_to "Create Commission", new_commission_path, class: "turquiose-btn" %>

    </div>
  </div>
</div>

app/views/payments/new.html.erb
<div class="background-commission order-background" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0) 50%), url('https://ohsooclean.com/wp-content/uploads/2018/06/testimonials.jpg');">
  <div class="container">
    <div class="com-container">
      <div class= "com-card">
        <h3>Your Order</h3>
        <div class="order-subheading">
          <h4 class="">Your Commission: <%= @order.request.commission.title %></h4>
          <p><%= @order.request.commission.description %></p>

          <h4 class="">Your Artist: <%= "#{@order.request.user.first_name} #{@order.request.user.last_name}"%></h4>
          <p><%= @order.request.description %></p>

          <div class="order-btn">
            <div>
              <h4>Amount</h4>
              <p><%= humanized_money_with_symbol(@order.amount) %></p>
            </div>
            <% @order.request_sku %>
            <%= form_tag order_payments_path(@order) do %>
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-name="My Request"
                data-email="<%= current_user.email %>"
                data-description="Request <%= @order.request_sku %>"
                data-amount="<%= @order.amount_cents %>"
                data-currency="<%= @order.amount.currency %>"></script>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/requests/index.html.erb
<h2>Requests for a Commission</h2>
<h4>This is where all the requests for a specific commission will be</h4>

app/views/requests/show.html.erb
<%= form_tag orders_path do %>
  <%= hidden_field_tag 'request_id', @request.id %>
  <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="logo-div">
    <h3>
      <%= link_to root_path, class: "navbar-heading" do %>
        <span class="turquiose-letter">c</span>ART
      <% end %>

    </h3>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
      <h5><%= link_to "Artists", users_path, class: "navbar-wagon-item navbar-wagon-link #{'navbar-underline' if params[:controller] == 'users' && params[:action] == 'index'}" %></h5>
      <h5><%= link_to "Commissions", commissions_path, class: "navbar-wagon-item navbar-wagon-link #{'navbar-underline' if params[:controller] == 'commissions'}" %></h5>

    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <h5><%= link_to "Profile", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link #{'navbar-underline' if params[:controller] == 'users' && params[:action] == 'show'}" %></h5>
      <h5><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %></h5>
      <!-- Avatar with dropdown menu -->

    <% else %>
      <!-- Login link (when logged out) -->
      <h5><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></h5>
    <% end %>
  </div>
</div>

app/views/users/edit_profile.html.erb
<%= simple_form_for current_user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :username %>
  <%= f.input :bio %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<div class="page-container">

<div class="artist-search-container">
  <div class="artist-search-icon">
    <h5 class="fas fa-search"></h5>
  </div>
  <div class="artist-border">
    <%= form_tag users_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control artist-search",
      placeholder: "Find an artist"
  %>
  <% end %>
  </div>
</div>

  <div class="container artist-container">
    <div class="row">
      <div class="col-xs-12 col-sm-7">
        <div class="artist-column">
          <% @users.select{ |user| user.id.even?}.each do |user| %>
            <% if user.artist? %>
              <div class="artist-card" style="background-image:
              url('<%= cl_image_path user.arts.first.photo, class: "artist-image"; %>');">
                <%= link_to user_path(user) do  %>
                  <div class="artist-card-background"></div>
                  <h4 class="artist-title"><%= "#{user.first_name} #{user.last_name}" %></h4>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-5">
         <div class="artist-column">
           <% @users.select{ |user| user.id.odd?}.each do |user| %>
            <% if user.artist? %>
              <div class="artist-card artist-card-height" style="background-image:
              url('<%= cl_image_path user.arts.first.photo, class: "artist-image"; %>');">
                <%= link_to user_path(user) do  %>
                  <div class="artist-card-background"></div>
                  <h4 class="artist-title"><%= "#{user.first_name} #{user.last_name}" %></h4>
                <% end %>
              </div>
            <% end %>
           <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="le-background" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0) 50%), url('https://images.unsplash.com/photo-1516868070914-77d36b96d52a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f9adc6448501e114fbd96df22e77aef1&auto=format&fit=crop&w=1050&q=80');">
  <div class="luser">
    <h2>
      @<%= @user.username %>
    </h2>
  </div>
</div>



<div class="request-card-container">
  <div class="row">
    <div class="col-xs-12 col-md-4 image-size">
      <%= cl_image_tag(@user.photo) %>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="prof-desc">
        <h3><%= @user.first_name %> <%= @user.last_name %></h3>
        <h5>@<%= @user.username %></h5>
        <p><%= @user.bio %></p>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="prof-btns">
        <%= link_to "Put out a commission", new_commission_path, class: "turquiose-btn" %>
        <%= link_to "Add art", new_art_path, class: "turquiose-btn" %>
      </div>
    </div>
  </div>


  <% if current_user.id == @user.id %>
    <% unless current_user.orders.empty? %>
      <h3>Your Orders</h3>
      <% current_user.orders.each do |order| %>
        <% if order.photo %>
          <div class="order-card">
            <div class="order-image">
              <%= cl_image_tag(order.photo)%>
            </div>
            <div class="order-content">
              <h6><%= order.request.commission.title %></h6>
              <p><%= order.message %></p>
              <p>@<%= order.request.commission.user.username %></p>
            </div>
          </div>
        <% else %>
          <div class="request-card">
            <div class="request-content ">
              <div class="request-content-header">
                <h6><%= order.request.commission.title %></h6>
              </div>
                <p>The artist is working on this order!</p>
            </div>
            <div class="request-btn">
              <%= link_to "Show Order", order_path(order), class: "turquiose-btn" %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <% unless current_user.commissions.empty? %>
      <h3>My Commissions</h3>
      <% current_user.commissions.each do |commission| %>
        <div class="request-card">
          <div class="request-content">
            <div class="request-content-header">
              <h6><%= commission.title %></h6>
            </div>
            <% unless commission.requests.empty? %>
              <p>You have <%= commission.requests.length %> requests</p>
            <% else %>
              <p>No requests yet</p>
            <% end %>
          </div>
          <div class="request-btn">
            <div>
              <%= link_to "Show Commission", commission_path(commission), class: "turquiose-btn" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>

    <% unless current_user.requests.empty? %>

      <h3>My Requests</h3>
      <% current_user.requests.each do |request| %>
        <div class="request-card">
          <div class="request-content">
            <div class="request-content-header">
              <h6><%= request.commission.title %></h6>
            </div>
            <p><%= request.description %></p>
            <% if request.status %>
              <% if request.order.photo_url %>
                <p>This commission has been completed!</p>
              <% else %>
                <%= simple_form_for request.order, html: { class: "request-form"} do |f| %>
                  <h6><%= f.input :message, placeholder: "Write your message here!", input_html: { class: "request-message" }, label_html: { class: "request-label"} %></h6>
                  <h6><%= f.input :photo, input_html: { class: "request-message" }, label_html: { class: "request-label"}%></h6>
                  <p><%= f.input :photo_cache, as: :hidden %></p>
          </div>
            <div class="request-btn">
              <div>
                <%= link_to "Show Request", commission_path(request.commission), class: "turquiose-btn" %>
              </div>
              <div class="update-btn">
                <%= f.submit "Update Order", :class => "request-form-submit" %>
              </div>
                <% end %>
              <% end %>
            <% end %>
            </div>
          <% unless request.status %>
            <div class="request-btn">
              <div>
                <%= link_to "Show Request", commission_path(request.commission), class: "turquiose-btn" %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <div class="row prof-portfolio">
    <% if @user.arts.length > 0 %>
      <h3>Gallery</h3>
      <% @user.arts.in_groups_of(3) do |art1, art2, art3| %>
        <div class="row">
          <div class="col-xs-12 col-md-4">
          <%= cl_image_tag art1.photo, class: "snazzy"  %>
        </div>
        <div class="col-xs-12 col-md-4">
          <%= cl_image_tag art2.photo, class: "snazzy"  %>
        </div>
        <div class="col-xs-12 col-md-4">
          <%= cl_image_tag art3.photo, class: "snazzy"  %>
        </div>
        </div>
      <% end %>
    <% end %>

<!--     <div class="col-xs-12 col-md-4">
      <img style="max-width:100%;" src="https://res.cloudinary.com/dghextejt/image/upload/v1536140578/ojc0glalg88czrgcjjil.jpg">
    </div>
    <div class="col-xs-12 col-md-4">
      <img style="max-width:100%;" src="https://res.cloudinary.com/dghextejt/image/upload/v1536140659/uermp4tbqyjqgbb4sjoh.jpg">
    </div>
  </div>
  <div class="row prof-portfolio">
    <div class="col-xs-12 col-md-4">
      <img style="max-width:100%;" src="https://res.cloudinary.com/dghextejt/image/upload/v1536160815/oa1scadi197xw4e7qyf8.jpg">
    </div>
    <div class="col-xs-12 col-md-4">
      <img style="max-width:100%;" src="https://res.cloudinary.com/dghextejt/image/upload/v1536160839/xpui9pf2xoj57dsm2p4b.jpg">
    </div>
    <div class="col-xs-12 col-md-4">
      <img style="max-width:100%;" src="https://res.cloudinary.com/dghextejt/image/upload/v1536140770/kql6nar04tz0ykynbdwi.jpg">
    </div> -->
  </div>
</div>